### PR TITLE
Fix gm name mismatch?

### PR DESCRIPTION
**Pull request by blister**
I think this fixes it, but can't test. Give it a try?

### CODE REVIEW

**Review by adam-stover — APPROVED** [review]

**Comment by BenjaminHunt** [comment]
> I think this fixes it, but can't test. Give it a try?

Well worst case it doesn't appear to break anything lol

**Comment by BenjaminHunt** [comment]
While we were there, I made an update to improve the GM helper function to search all members with the passed franchise role instead of all guild members, checking for the franchise and gm role.

Just some simple code cleanup.

**Comment by BenjaminHunt** [comment]
LGTM

**Review by BenjaminHunt — APPROVED** [review]
image

**Pull request merged**
